name = "http-proxy"
version = "0.1.0"
language = "rust"
type = "component"

[component]
wit_world = "hello"
wasm_target = "wasm32-wasip2"

[overrides]
"wasmcloud:ai" = { path = "../openai-standalone/wit/world.wit" }
